import productOneImage from '../images/products-one.jpeg';
import productTwoImage from '../images/products-two.jpeg';
import productThreeImage from '../images/products-three.jpeg';
import productFourImage from '../images/products-four.jpeg';
import productFiveImage from '../images/products-five.jpeg';
import productSixImage from '../images/products-six.jpeg';

export const requestFormInitialValues = { cartName: '', cartEmail: '', cartPhone: '', cartProducts: [] };
export const onStateSuccess = 'Успешно!';
export const onStateError = 'Ошибка!';

export const products = {
  1: {
    id: 1,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  2: {
    id: 2,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  3: {
    id: 3,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  4: {
    id: 4,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  5: {
    id: 5,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  6: {
    id: 6,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  7: {
    id: 7,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  8: {
    id: 8,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  9: {
    id: 9,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  10: {
    id: 10,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  11: {
    id: 11,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  12: {
    id: 12,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  13: {
    id: 13,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  14: {
    id: 14,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  15: {
    id: 15,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  16: {
    id: 16,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  17: {
    id: 17,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  18: {
    id: 18,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  19: {
    id: 19,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  20: {
    id: 20,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  21: {
    id: 21,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  22: {
    id: 22,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  23: {
    id: 23,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  24: {
    id: 24,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  25: {
    id: 25,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  26: {
    id: 26,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  27: {
    id: 27,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  28: {
    id: 28,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  29: {
    id: 29,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  30: {
    id: 30,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  31: {
    id: 31,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  32: {
    id: 32,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  33: {
    id: 33,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  34: {
    id: 34,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  35: {
    id: 35,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  36: {
    id: 36,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  37: {
    id: 37,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  38: {
    id: 38,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  39: {
    id: 39,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  40: {
    id: 40,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  41: {
    id: 41,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  42: {
    id: 42,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  43: {
    id: 43,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  44: {
    id: 44,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  45: {
    id: 45,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  46: {
    id: 46,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  47: {
    id: 47,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  48: {
    id: 48,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  49: {
    id: 49,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  50: {
    id: 50,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  51: {
    id: 51,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  52: {
    id: 52,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  53: {
    id: 53,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  54: {
    id: 54,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  55: {
    id: 55,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  56: {
    id: 56,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  57: {
    id: 57,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  58: {
    id: 58,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  59: {
    id: 59,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  60: {
    id: 60,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  61: {
    id: 61,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  62: {
    id: 62,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  63: {
    id: 63,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  64: {
    id: 64,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  65: {
    id: 65,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  66: {
    id: 66,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  67: {
    id: 67,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  68: {
    id: 68,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  69: {
    id: 69,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  70: {
    id: 70,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  71: {
    id: 71,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  72: {
    id: 72,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  73: {
    id: 73,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  74: {
    id: 74,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  75: {
    id: 75,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  76: {
    id: 76,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  77: {
    id: 77,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  78: {
    id: 78,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  79: {
    id: 79,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  80: {
    id: 80,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  81: {
    id: 81,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  82: {
    id: 82,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  83: {
    id: 83,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  84: {
    id: 84,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  85: {
    id: 85,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  86: {
    id: 86,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  87: {
    id: 87,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  88: {
    id: 88,
    image: productTwoImage,
    name: 'Воркаут-комплекс 2',
    description: 'Канат, кольца, шведская стенка, 3 турника, брусья и наклонная скамья',
    price: 298594,
    category: 'Комплекс',
  },
  89: {
    id: 89,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  90: {
    id: 90,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  91: {
    id: 91,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  92: {
    id: 92,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  93: {
    id: 93,
    image: productSixImage,
    name: 'Тренажёр 3',
    description: 'Вертикальные поручни для колясочников',
    price: 47438,
    category: 'Поручни',
  },
  94: {
    id: 94,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  95: {
    id: 95,
    image: productOneImage,
    name: 'Воркаут-комплекс 1',
    description:
      'Брусья, турник, шведская стенка и наклонная скамья для пресса. Описание, которое не помещается в контейнер',
    price: 197156,
    category: 'Комплекс',
  },
  96: {
    id: 96,
    image: productFiveImage,
    name: 'Воркаут-комплекс 3',
    description: 'Воркаут-комплекс: 23 турника и 2 рукохода. Описание, которое не помещается в контейнер',
    price: 558656,
    category: 'Комплекс',
  },
  97: {
    id: 97,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
  98: {
    id: 98,
    image: productThreeImage,
    name: 'Тренажёр 1',
    description: 'Брусья гнутые',
    price: 33813,
    category: 'Брусья',
  },
  99: {
    id: 99,
    image: productFourImage,
    name: 'Тренажёр 2',
    description: 'Гамвик',
    price: 390063,
    category: 'Гамвик',
  },
};

export const getFormData = (json) => {
  try {
    const data = new FormData();
    for (let key in json) {
      data.append(key, json[key]);
    }
    return data;
  } catch (error) {
    console.error(error);
    return null;
  }
};
